name: Test caching with multistage build

on:
  workflow_dispatch:
  push:


env:
  REGISTRY: ghcr.io
  BASE_NAME: wholtz/cachetest3

jobs:
  build_docker_image_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout source
      uses: actions/checkout@27135e314dd1818f797af1db9dae03a9f045786b
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@07aea5fc9c8874ece2fab5ca5c18fdfc5d526272
    - name: Login to GHCR
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker images
      id: docker_build
      uses: docker/build-push-action@35434f557ad77672899d67f7992fb5560bda1071
      with:
        push: true
        tags: ${{ env.REGISTRY}}/${{ env.BASE_NAME }}:latest
        cache-from: |
          type=registry,ref=${{ env.REGISTRY}}/${{ env.BASE_NAME }}:latest
        cache-to: type=registry,ref=${{ env.REGISTRY}}/${{ env.BASE_NAME }}_buildcache:latest,mode=max
